// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TableController from "./table_controller"
application.register("table", TableController)

import Ts__SelectController from "./ts/select_controller"
application.register("ts--select", Ts__SelectController)
